import type { NewProduct } from "@/db/schema";

// A curated Amazon-2023-style catalog. Covers many categories so
// the recommender has room to personalize.
export const SEED_PRODUCTS: NewProduct[] = [
  // Electronics - Headphones
  {
    asin: "B0CHX3QBCH",
    title: "Sony WH-1000XM5 Wireless Noise Cancelling Headphones",
    brand: "Sony",
    category: "Electronics",
    subcategory: "Headphones",
    price: 349.99,
    rating: 4.6,
    reviewCount: 18432,
    description:
      "Industry-leading noise cancellation with 30-hour battery life, hi-res audio, and adaptive sound control.",
    features: ["Noise Cancelling", "30h Battery", "Bluetooth 5.2", "Hi-Res Audio"],
    tags: ["headphones", "wireless", "premium", "noise-cancelling", "travel"],
    imageEmoji: "🎧",
  },
  {
    asin: "B0BDHWDR12",
    title: "Apple AirPods Pro (2nd Generation)",
    brand: "Apple",
    category: "Electronics",
    subcategory: "Headphones",
    price: 199.0,
    rating: 4.7,
    reviewCount: 42210,
    description:
      "Active Noise Cancellation, Adaptive Transparency, Personalized Spatial Audio with USB-C charging case.",
    features: ["ANC", "Spatial Audio", "USB-C", "MagSafe"],
    tags: ["earbuds", "wireless", "apple", "premium", "noise-cancelling"],
    imageEmoji: "🎧",
  },
  {
    asin: "B09JQMJHXY",
    title: "Bose QuietComfort Earbuds II",
    brand: "Bose",
    category: "Electronics",
    subcategory: "Headphones",
    price: 249.0,
    rating: 4.4,
    reviewCount: 8210,
    description: "World-class noise cancellation and lifelike sound in a small package.",
    features: ["ANC", "6h Battery", "IPX4"],
    tags: ["earbuds", "wireless", "noise-cancelling", "premium"],
    imageEmoji: "🎧",
  },

  // Electronics - Laptops
  {
    asin: "B0CM5J8X9P",
    title: "Apple MacBook Air 15-inch M3",
    brand: "Apple",
    category: "Electronics",
    subcategory: "Laptops",
    price: 1299.0,
    rating: 4.8,
    reviewCount: 5320,
    description:
      "Supercharged by the M3 chip. 15.3-inch Liquid Retina display, up to 18 hours battery life.",
    features: ["M3 Chip", "8GB RAM", "256GB SSD", "18h Battery"],
    tags: ["laptop", "apple", "premium", "productivity", "student"],
    imageEmoji: "💻",
  },
  {
    asin: "B0CGJ2H9PN",
    title: "Dell XPS 13 Plus Laptop",
    brand: "Dell",
    category: "Electronics",
    subcategory: "Laptops",
    price: 1199.99,
    rating: 4.3,
    reviewCount: 2140,
    description:
      "13.4-inch OLED touchscreen, Intel Core i7, 16GB RAM, 512GB SSD.",
    features: ["OLED", "Intel i7", "16GB RAM", "512GB SSD"],
    tags: ["laptop", "windows", "premium", "productivity"],
    imageEmoji: "💻",
  },
  {
    asin: "B0BSHF7WHW",
    title: "ASUS Chromebook Flip C433",
    brand: "ASUS",
    category: "Electronics",
    subcategory: "Laptops",
    price: 399.0,
    rating: 4.2,
    reviewCount: 3980,
    description: "Convertible 2-in-1, 14-inch touch, 8GB RAM, 64GB eMMC.",
    features: ["2-in-1", "Touch", "8GB RAM"],
    tags: ["laptop", "chromebook", "budget", "student"],
    imageEmoji: "💻",
  },

  // Electronics - Smart Home
  {
    asin: "B09B8V1LZ3",
    title: "Echo Dot (5th Gen) Smart Speaker with Alexa",
    brand: "Amazon",
    category: "Electronics",
    subcategory: "Smart Home",
    price: 49.99,
    rating: 4.7,
    reviewCount: 231005,
    description: "Bigger vibrant sound, temperature sensor, tap-to-snooze alarms.",
    features: ["Alexa", "Temp Sensor", "Compact"],
    tags: ["smart-speaker", "alexa", "budget", "smart-home"],
    imageEmoji: "🔊",
  },
  {
    asin: "B08MQZXN1X",
    title: "Ring Video Doorbell Wired",
    brand: "Ring",
    category: "Electronics",
    subcategory: "Smart Home",
    price: 64.99,
    rating: 4.5,
    reviewCount: 45120,
    description: "1080p HD video, advanced motion detection, real-time notifications.",
    features: ["1080p", "Motion Detect", "Two-way Talk"],
    tags: ["security", "smart-home", "doorbell"],
    imageEmoji: "🔔",
  },
  {
    asin: "B07XLML2YS",
    title: "Philips Hue White & Color Ambiance Starter Kit",
    brand: "Philips",
    category: "Electronics",
    subcategory: "Smart Home",
    price: 199.99,
    rating: 4.6,
    reviewCount: 12043,
    description: "3 smart bulbs + bridge. 16 million colors, works with Alexa & Google.",
    features: ["16M Colors", "Bridge Included", "Voice Control"],
    tags: ["smart-lighting", "smart-home", "premium"],
    imageEmoji: "💡",
  },

  // Kitchen
  {
    asin: "B0936BDR1B",
    title: "Ninja AF101 Air Fryer 4 Quart",
    brand: "Ninja",
    category: "Home & Kitchen",
    subcategory: "Small Appliances",
    price: 99.99,
    rating: 4.7,
    reviewCount: 78201,
    description:
      "4 programmable functions: Air Fry, Roast, Reheat, Dehydrate. Wide temperature range.",
    features: ["4qt", "4 Functions", "Dishwasher Safe"],
    tags: ["kitchen", "air-fryer", "cooking", "healthy"],
    imageEmoji: "🍳",
  },
  {
    asin: "B08P234YCM",
    title: "Instant Pot Duo 7-in-1 Electric Pressure Cooker",
    brand: "Instant Pot",
    category: "Home & Kitchen",
    subcategory: "Small Appliances",
    price: 89.99,
    rating: 4.7,
    reviewCount: 152340,
    description: "6-quart, 7 functions: pressure cook, slow cook, rice cooker, steamer, sauté, yogurt maker, warmer.",
    features: ["6qt", "7-in-1", "Stainless"],
    tags: ["kitchen", "pressure-cooker", "cooking", "family"],
    imageEmoji: "🍲",
  },
  {
    asin: "B00FLYWNYQ",
    title: "Keurig K-Classic Coffee Maker",
    brand: "Keurig",
    category: "Home & Kitchen",
    subcategory: "Coffee",
    price: 129.99,
    rating: 4.5,
    reviewCount: 88231,
    description: "Single serve K-Cup pod coffee brewer, 48oz reservoir.",
    features: ["Single Serve", "48oz Tank", "3 Sizes"],
    tags: ["kitchen", "coffee", "morning"],
    imageEmoji: "☕",
  },

  // Books
  {
    asin: "B0C1J5RGVQ",
    title: "Atomic Habits by James Clear",
    brand: "Avery",
    category: "Books",
    subcategory: "Self-Help",
    price: 14.99,
    rating: 4.8,
    reviewCount: 132480,
    description:
      "An easy & proven way to build good habits & break bad ones. Tiny changes, remarkable results.",
    features: ["Bestseller", "Paperback", "320 pages"],
    tags: ["books", "self-help", "productivity", "bestseller"],
    imageEmoji: "📘",
  },
  {
    asin: "B08FF8MTM6",
    title: "The Psychology of Money by Morgan Housel",
    brand: "Harriman House",
    category: "Books",
    subcategory: "Finance",
    price: 12.99,
    rating: 4.7,
    reviewCount: 54210,
    description: "Timeless lessons on wealth, greed, and happiness.",
    features: ["Bestseller", "Paperback"],
    tags: ["books", "finance", "self-help", "bestseller"],
    imageEmoji: "📗",
  },
  {
    asin: "B0BF5H8Q7R",
    title: "Project Hail Mary by Andy Weir",
    brand: "Ballantine",
    category: "Books",
    subcategory: "Fiction",
    price: 16.99,
    rating: 4.7,
    reviewCount: 98230,
    description: "A lone astronaut must save the earth from disaster in this thrilling sci-fi novel.",
    features: ["Sci-Fi", "Hardcover"],
    tags: ["books", "fiction", "sci-fi", "bestseller"],
    imageEmoji: "📕",
  },

  // Fashion
  {
    asin: "B07QK1XR44",
    title: "Levi's Men's 501 Original Fit Jeans",
    brand: "Levi's",
    category: "Clothing",
    subcategory: "Men",
    price: 59.5,
    rating: 4.5,
    reviewCount: 43210,
    description: "Straight leg, button fly, iconic 501 fit. 100% cotton.",
    features: ["100% Cotton", "Straight Leg", "Button Fly"],
    tags: ["clothing", "jeans", "mens", "classic"],
    imageEmoji: "👖",
  },
  {
    asin: "B08P4XRLM2",
    title: "Nike Air Max 270 Men's Shoes",
    brand: "Nike",
    category: "Clothing",
    subcategory: "Shoes",
    price: 150.0,
    rating: 4.6,
    reviewCount: 21456,
    description: "The iconic Air Max unit delivers unrivaled all-day comfort.",
    features: ["Air Max", "Mesh Upper", "Rubber Sole"],
    tags: ["shoes", "sneakers", "mens", "sports", "premium"],
    imageEmoji: "👟",
  },
  {
    asin: "B09MZ8QYV1",
    title: "Adidas Women's Cloudfoam Pure Running Shoe",
    brand: "Adidas",
    category: "Clothing",
    subcategory: "Shoes",
    price: 69.99,
    rating: 4.5,
    reviewCount: 34120,
    description: "Comfortable cloudfoam midsole, breathable knit upper.",
    features: ["Cloudfoam", "Knit Upper"],
    tags: ["shoes", "sneakers", "womens", "sports", "running"],
    imageEmoji: "👟",
  },

  // Beauty
  {
    asin: "B00QXW95Q4",
    title: "CeraVe Moisturizing Cream 19 oz",
    brand: "CeraVe",
    category: "Beauty & Personal Care",
    subcategory: "Skincare",
    price: 17.99,
    rating: 4.8,
    reviewCount: 128340,
    description:
      "Daily face and body moisturizer for dry skin with hyaluronic acid and 3 essential ceramides.",
    features: ["Hyaluronic Acid", "Ceramides", "Fragrance Free"],
    tags: ["skincare", "moisturizer", "dermatologist", "sensitive-skin"],
    imageEmoji: "🧴",
  },
  {
    asin: "B01MSSDEPK",
    title: "The Ordinary Niacinamide 10% + Zinc 1%",
    brand: "The Ordinary",
    category: "Beauty & Personal Care",
    subcategory: "Skincare",
    price: 6.5,
    rating: 4.5,
    reviewCount: 43210,
    description: "High-strength vitamin and mineral blemish formula.",
    features: ["Niacinamide", "Zinc", "Budget"],
    tags: ["skincare", "serum", "budget", "acne"],
    imageEmoji: "🧪",
  },

  // Toys & Games
  {
    asin: "B0BJHKQ7RZ",
    title: "LEGO Star Wars The Mandalorian's N-1 Starfighter",
    brand: "LEGO",
    category: "Toys & Games",
    subcategory: "Building Sets",
    price: 59.99,
    rating: 4.9,
    reviewCount: 8210,
    description: "412-piece buildable N-1 Starfighter with Mando and Grogu minifigures.",
    features: ["412 pieces", "Ages 9+", "Minifigures"],
    tags: ["toys", "lego", "kids", "star-wars", "gift"],
    imageEmoji: "🚀",
  },
  {
    asin: "B0BXFHXFFP",
    title: "Nintendo Switch OLED Model",
    brand: "Nintendo",
    category: "Toys & Games",
    subcategory: "Video Games",
    price: 349.99,
    rating: 4.8,
    reviewCount: 87210,
    description: "7-inch OLED screen, enhanced audio, 64GB storage, wired LAN dock.",
    features: ["7-inch OLED", "64GB", "Detachable Joy-Con"],
    tags: ["gaming", "console", "premium", "gift"],
    imageEmoji: "🎮",
  },

  // Sports & Fitness
  {
    asin: "B08YZP5RQ7",
    title: "Bowflex SelectTech 552 Adjustable Dumbbells",
    brand: "Bowflex",
    category: "Sports & Outdoors",
    subcategory: "Fitness",
    price: 429.0,
    rating: 4.7,
    reviewCount: 21430,
    description: "Adjustable from 5 to 52.5 lbs. Replaces 15 sets of weights.",
    features: ["5-52.5 lbs", "Adjustable", "Space Saving"],
    tags: ["fitness", "home-gym", "premium", "strength"],
    imageEmoji: "🏋️",
  },
  {
    asin: "B07XJ8C8F7",
    title: "Manduka PRO Yoga Mat 6mm",
    brand: "Manduka",
    category: "Sports & Outdoors",
    subcategory: "Fitness",
    price: 138.0,
    rating: 4.7,
    reviewCount: 12043,
    description: "High-density cushion, non-slip, lifetime guarantee.",
    features: ["6mm", "Non-Slip", "Lifetime Warranty"],
    tags: ["fitness", "yoga", "premium"],
    imageEmoji: "🧘",
  },

  // Pet
  {
    asin: "B07C5RQKC1",
    title: "PetSafe ScoopFree Self-Cleaning Cat Litter Box",
    brand: "PetSafe",
    category: "Pet Supplies",
    subcategory: "Cats",
    price: 169.95,
    rating: 4.3,
    reviewCount: 15340,
    description: "Automatic rake, disposable crystal tray, controls odors up to 5x better.",
    features: ["Self-Cleaning", "Odor Control", "Disposable Tray"],
    tags: ["pets", "cats", "premium", "convenience"],
    imageEmoji: "🐱",
  },
  {
    asin: "B09KG7NW1V",
    title: "Furbo 360° Dog Camera",
    brand: "Furbo",
    category: "Pet Supplies",
    subcategory: "Dogs",
    price: 210.0,
    rating: 4.2,
    reviewCount: 9820,
    description: "360° view, treat tossing, barking alerts, night vision.",
    features: ["360°", "Treat Toss", "Night Vision"],
    tags: ["pets", "dogs", "smart-home", "premium"],
    imageEmoji: "🐶",
  },

  // Office
  {
    asin: "B08L5NP6NG",
    title: "Herman Miller Aeron Ergonomic Chair",
    brand: "Herman Miller",
    category: "Office Products",
    subcategory: "Furniture",
    price: 1395.0,
    rating: 4.6,
    reviewCount: 3210,
    description: "Iconic ergonomic office chair with PostureFit SL back support.",
    features: ["Ergonomic", "12-yr Warranty", "Adjustable"],
    tags: ["office", "chair", "premium", "productivity", "ergonomic"],
    imageEmoji: "🪑",
  },
  {
    asin: "B091G4YP4Z",
    title: "Logitech MX Master 3S Wireless Mouse",
    brand: "Logitech",
    category: "Office Products",
    subcategory: "Accessories",
    price: 99.99,
    rating: 4.7,
    reviewCount: 34120,
    description: "8K DPI, quiet clicks, multi-device, USB-C charging.",
    features: ["8K DPI", "Quiet Clicks", "USB-C"],
    tags: ["office", "mouse", "productivity", "premium"],
    imageEmoji: "🖱️",
  },
];
